name: Conditional Step Example

on:
  workflow_dispatch:
    inputs:
      should_run:
        description: "Specify if the extra step should run"
        required: false
        default: "no"

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Always Run Step
        run: echo "This step always runs."

      - name: Conditional Step
        if: ${{ github.event.inputs.should_run == 'yes' }}
        run: echo "This step runs only if the 'should_run' input is 'yes'."
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10" # don't know what the impact of this is
      - name: Update version
        uses: kurtmc/github-action-python-versioner@v1
